import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing, typography } from '../../theme';

export const HomeScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  content: { paddingBottom: 110 },
  header: { paddingHorizontal: spacing.lg, paddingTop: spacing.sm },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoRow: { flexDirection: 'row', alignItems: 'center' },
  logoMark: {
    width: 30,
    height: 30,
    borderRadius: radius.pill,
    backgroundColor: colors.cyan,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.xs,
  },
  logoMarkText: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 18,
    color: colors.white,
    lineHeight: 20,
  },
  logoText: { ...typography.heading3Bold, color: colors.black, fontSize: 18 },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
  },
  searchIcon: {
    width: 25,
    height: 25,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: radius.pill,
    position: 'relative',
  },
  searchHandle: {
    position: 'absolute',
    width: 9,
    height: 2,
    backgroundColor: colors.black,
    right: -6,
    bottom: 0,
    transform: [{ rotate: '48deg' }],
    borderRadius: radius.pill,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: radius.pill,
    backgroundColor: colors.grey50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { ...typography.captionSemiBold, color: colors.grey150 },
  locationRow: {
    marginTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationPin: { fontSize: 15, marginRight: spacing.xs },
  locationText: { ...typography.captionRegular, color: colors.grey150 },
  locationStrong: { ...typography.captionSemiBold, color: colors.black },
  banner: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    height: 148,
    borderRadius: radius.xl,
    backgroundColor: '#55B8E7',
    overflow: 'hidden',
    position: 'relative',
  },
  bannerGlow: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: radius.pill,
    right: -65,
    top: -80,
    backgroundColor: '#9BE0F7',
    opacity: 0.7,
  },
  bannerContent: {
    flex: 1,
    padding: spacing.lg,
    justifyContent: 'center',
    zIndex: 2,
  },
  discountBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: 6,
    backgroundColor: colors.black,
  },
  discountText: { ...typography.captionSemiBold, color: colors.white },
  bannerEyebrow: {
    ...typography.captionRegular,
    color: colors.white,
    marginTop: spacing.xs,
  },
  bannerTitle: {
    ...typography.heading2Bold,
    color: colors.white,
    fontSize: 24,
    marginTop: 1,
  },
  bannerEmoji: {
    position: 'absolute',
    right: 18,
    top: 22,
    fontSize: 82,
    zIndex: 1,
  },
  bannerDots: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  activeDot: {
    width: 7,
    height: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.cyan,
    marginHorizontal: 2,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: radius.pill,
    backgroundColor: colors.grey100,
    marginHorizontal: 2,
  },
  blackColorDot: {
    backgroundColor: '#252525',
  },

  greenColorDot: {
    backgroundColor: '#21D4B4',
  },
  section: { marginTop: spacing.xxl },
  sectionHeader: {
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    ...typography.heading3Bold,
    color: colors.black,
    fontSize: 18,
  },
  seeAll: {
    ...typography.captionSemiBold,
    color: colors.cyan,
    textTransform: 'uppercase',
  },
  categoryList: { paddingHorizontal: spacing.lg },
  categoryCard: {
    width: 76,
    height: 78,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#EEF0F6',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  categoryIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  categoryEmoji: { fontSize: 27 },
  categoryName: {
    ...typography.overlineRegular,
    color: colors.black,
    fontSize: 9,
    textAlign: 'center',
  },
  categoryImage: {
    width: 32,
    height: 32,
  },
  productGrid: {
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  productCard: { width: '48.3%', marginBottom: spacing.lg },
  productImageContainer: {
    height: 138,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.grey50,
    position: 'relative',
  },
  productImage: { width: '100%', height: '100%' },
  productFallback: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  productFallbackEmoji: { fontSize: 56 },
  heartButton: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 27,
    height: 27,
    borderRadius: radius.pill,
    backgroundColor: '#262626',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heartText: { color: colors.white, fontSize: 17, lineHeight: 18 },
  colorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  colorDot: {
    width: 22,
    height: 22,
    borderRadius: radius.pill,
    borderWidth: 2,
    borderColor: colors.white,
    marginRight: -5,
    ...shadows.small,
  },
  colorMore: {
    ...typography.captionRegular,
    color: colors.grey150,
    textDecorationLine: 'underline',
    marginLeft: spacing.sm,
  },
  productName: {
    ...typography.body2Regular,
    color: colors.black,
    marginTop: spacing.sm,
  },
  productPrice: {
    ...typography.body2Medium,
    color: colors.black,
    marginTop: 1,
  },
  originalPrice: {
    ...typography.captionRegular,
    color: colors.grey100,
    textDecorationLine: 'line-through',
    marginTop: 1,
  },
  loadingBox: { height: 180, alignItems: 'center', justifyContent: 'center' },
  loadingText: {
    ...typography.body2Regular,
    color: colors.grey150,
    marginTop: spacing.sm,
  },
  emptyText: {
    ...typography.body2Regular,
    color: colors.grey150,
    textAlign: 'center',
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.xxl,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 82,
    paddingTop: spacing.sm,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#F0F1F5',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navIcon: { fontSize: 23, lineHeight: 26, color: colors.grey150 },
  navIconActive: { color: colors.cyan },
  navLabel: {
    ...typography.captionRegular,
    color: colors.grey150,
    marginTop: 2,
    fontSize: 10,
  },
  navLabelActive: { color: colors.black, fontFamily: 'PlusJakartaSans-Medium' },
  cartBadge: {
    position: 'absolute',
    top: -2,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.red,
  },
});
